# Generated by Django 6.1 on 2026-08-25 15:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер бокса')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='Этаж')),
                ('area', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Площадь (м²)')),
                ('dimensions', models.CharField(help_text='Например: 2 х 1.5 х 2.5 м', max_length=50, verbose_name='Габариты (Д х Ш х В)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена аренды за месяц (₽)')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('rented', 'Арендован'), ('reserved', 'Забронирован')], default='free', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail клиента')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки с сайта',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('temperature', models.CharField(default='+18 °С', max_length=50, verbose_name='Температура')),
                ('ceiling_height', models.DecimalField(decimal_places=1, default=3.5, max_digits=4, verbose_name='Высота потолков (м)')),
                ('advantage', models.CharField(blank=True, help_text='Например: Рядом с метро, Парковка', max_length=100, verbose_name='Преимущество (тег)')),
                ('description', models.TextField(blank=True, verbose_name='Описание склада')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
                ('directions', models.TextField(blank=True, verbose_name='Схема проезда')),
                ('image', models.ImageField(blank=True, null=True, upload_to='warehouses/', verbose_name='Фото склада')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала аренды')),
                ('end_date', models.DateField(verbose_name='Дата окончания аренды')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('expired', 'Просрочена'), ('closed', 'Завершена')], default='active', max_length=20, verbose_name='Статус аренды')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR-код доступа')),
                ('access_code', models.CharField(blank=True, max_length=20, verbose_name='Пин-код замка')),
                ('need_delivery', models.BooleanField(default=False, verbose_name='Требуется бесплатная доставка')),
                ('client_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес для забора вещей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='self_storage.box', verbose_name='Бокс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Заказ аренды',
                'verbose_name_plural': 'Заказы аренды',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='self_storage.warehouse', verbose_name='Склад'),
        ),
    ]
