# Generated by Django 6.1 on 2026-08-26 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона (например: +7 999 123-45-67 или 89991234567).', regex='^\\+?[0-9\\s\\-\\(\\)]{10,20}$')], verbose_name='Телефон'),
        ),
    ]
