# Generated by Django 6.1 on 2026-08-26 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0003_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_rental_request',
            field=models.BooleanField(default=True, help_text='True — заявка, False — подтверждённая аренда', verbose_name='Заявка на аренду (не подтверждена)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона (например: +7 999 123-45-67 или 89991234567).', regex='^\\+?[0-9\\s\\-\\(\\)]{10,20}$')], verbose_name='Телефон'),
        ),
    ]
