# Generated by Django 6.1 on 2026-08-29 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0004_order_is_rental_request_alter_lead_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=500, verbose_name='Оригинальная ссылка')),
                ('short_code', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Короткий код может содержать только латинские буквы, цифры, дефис и нижнее подчеркивание.', regex='^[a-zA-Z0-9_-]+$')], verbose_name='Короткий код')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Количество переходов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
