# Generated by Django 6.1 on 2026-08-31 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0005_shortlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={'verbose_name': 'Короткая ссылка', 'verbose_name_plural': 'Короткие ссылки'},
        ),
    ]
