# Generated by Django 6.1 on 2026-08-31 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage', '0006_alter_shortlink_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short_code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Короткий код может содержать только латинские буквы, цифры, дефис и нижнее подчеркивание.', regex='^[a-zA-Z0-9_-]+$')], verbose_name='Короткий код'),
        ),
    ]
